version: '2'
services:
  web:
    network_mode: "bridge"
    build: .
    ports:
      - "3000:3000"
      # For debugging with Ruby debugger
      # - "1234:1234"
    links:
      - db
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db
    env_file:
      - common.env
      - .env
    environment:
      RAILS_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: admin
      DB_PASSWORD: password
      VIRTUAL_HOST: orca.dev0.be.lan
    command: /usr/src/app/init.sh
  db:
    network_mode: "bridge"
    image: postgres:9.5.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orca
